# team-a pulling from team-a/ namespace with an ECR pull role SA — should SUCCEED ✅
# Uses sa-team-a-to-own → ECR pull role → AssumeRoleWithWebIdentity → team-a/app access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-team-a-to-own
  namespace: team-a
  annotations:
    eks.amazonaws.com/ecr-role-arn: ${ECR_PULL_ROLE_ARN_TEAM_A}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-to-own
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-to-own
  template:
    metadata:
      labels:
        app: team-a-to-own
    spec:
      tolerations:
        - key: "ecr-pod-permission"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/ecr-pod-permission: "true"
      serviceAccountName: sa-team-a-to-own
      containers:
        - name: app
          image: ${ECR_TEAM_A_REPO_URL}:latest
          ports:
            - containerPort: 80
