# team-b pulling from shared/ namespace using default SA — should SUCCEED ✅
# Uses default SA → no IRSA → falls back to node role → node role has shared/* access
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-shared-def
  namespace: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-b-shared-def
  template:
    metadata:
      labels:
        app: team-b-shared-def
    spec:
      tolerations:
        - key: "ecr-pod-permission"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/ecr-pod-permission: "true"
      containers:
        - name: nginx
          image: ${ECR_SHARED_REPO_URL}:latest
          ports:
            - containerPort: 80
