# team-b pulling from shared/ namespace — should SUCCEED ✅
# Uses team-b IRSA role → shared/app repo policy allows team-b role → pull succeeds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-team-b-to-shared
  namespace: team-b
  annotations:
    eks.amazonaws.com/ecr-role-arn: ${IRSA_ROLE_ARN_TEAM_B}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-to-shared
  namespace: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-b-to-shared
  template:
    metadata:
      labels:
        app: team-b-to-shared
    spec:
      tolerations:
        - key: "ecr-pod-permission"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/ecr-pod-permission: "true"
      serviceAccountName: sa-team-b-to-shared
      containers:
        - name: app
          image: ${ECR_SHARED_REPO_URL}:latest
          ports:
            - containerPort: 80
