# team-b pulling from team-b/ namespace with IRSA SA — should SUCCEED ✅
# Uses sa-team-b-to-own → IRSA → AssumeRoleWithWebIdentity → team-b/app access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-team-b-to-own
  namespace: team-b
  annotations:
    eks.amazonaws.com/ecr-role-arn: ${IRSA_ROLE_ARN_TEAM_B}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-to-own
  namespace: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-b-to-own
  template:
    metadata:
      labels:
        app: team-b-to-own
    spec:
      tolerations:
        - key: "ecr-pod-permission"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/ecr-pod-permission: "true"
      serviceAccountName: sa-team-b-to-own
      containers:
        - name: app
          image: ${ECR_TEAM_B_REPO_URL}:latest
          ports:
            - containerPort: 80
